#pragma once

; //...???왜 되는거야 ?? 0312

enum DIRECTION { DIR_LEFT, DIR_RIGHT, DIR_UP, DIR_DOWN, DIR_END };

enum  OBJID { OBJ_PLAYER, OBJ_SOUP, OBJ_BLOCK, OBJ_MOUSE, OBJ_SHIELD, OBJ_UI, OBJ_END };

enum SCENEID { SC_LOGO, SC_MENU, SC_STAGE01, SC_EDIT, SC_END };

enum RENDERID { RENDER_BACK, RENDER_GAMEOBJECT, RENDER_UI, RENDER_END };

// 최대 32개 채널까지 동시 재생이 가능
enum CHANNELID { SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER, MAXCHANNEL };

enum MAPID { MAP_BLOCK, MAP_OBSTACLE, MAP_END };

enum INMAP { BLOCK, OBSTACLE };
